//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToProductTopping
    {
        public int orderToProductId { get; set; }
        public int toppingId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual OrderToProduct OrderToProduct { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
