//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToppingsForProduct
    {
        public int toppingForProductId { get; set; }
        public Nullable<int> productCategoryId { get; set; }
        public Nullable<int> toppingCategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
